/-
Copyright (c) 2026 Lean FRO, LLC. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
-/
module

prelude
public meta import Lean.Compiler.UnsupportedOnTargetCmd
meta import Init.Data.Float
meta import Init.Data.Float32
meta import Init.Data.Int.DivMod.Basic
meta import Init.Data.Repr
meta import Init.Data.SInt.Basic
meta import Init.Data.SInt.Float
meta import Init.Data.SInt.Float32
meta import Init.Data.String.Basic
meta import Init.Data.String.Modify
meta import Init.Data.String.Pattern.Basic
meta import Init.Data.String.Slice
meta import Init.ShareCommon
meta import Init.System.Platform
meta import Init.System.Promise
meta import Init.System.ST
meta import Init.Util
meta import Std.Data.ByteSlice
meta import Std.Internal.UV
meta import Std.Net
meta import Std.Sync
meta import Std.Time

/-! Stdlib declarations denied at compile time on every freestanding
cross-compile target.

The freestanding runtime is intentionally smaller than the host runtime. Entries
here are the fail-closed policy boundary: when a runtime family is not provided,
generated code must be rejected by the compiler instead of reaching the linker or
misbehaving at runtime. Triple pattern `*` matches every non-host target that
uses `compiler.runtime=none`.
-/

register_unsupported_on_target IO.FS.readFile      "*" "uses host filesystem"
register_unsupported_on_target IO.FS.writeFile     "*" "uses host filesystem"
register_unsupported_on_target IO.FS.realPath      "*" "uses host filesystem"
register_unsupported_on_target IO.FS.readBinFile   "*" "uses host filesystem"
register_unsupported_on_target IO.FS.writeBinFile  "*" "uses host filesystem"
register_unsupported_on_target IO.FS.createDir     "*" "uses host filesystem"
register_unsupported_on_target IO.FS.createDirAll  "*" "uses host filesystem"
register_unsupported_on_target IO.FS.removeDir     "*" "uses host filesystem"
register_unsupported_on_target IO.FS.removeFile    "*" "uses host filesystem"
register_unsupported_on_target IO.FS.rename        "*" "uses host filesystem"
register_unsupported_on_target IO.FS.hardLink      "*" "uses host filesystem"
register_unsupported_on_target IO.FS.createTempFile "*" "uses host filesystem"
register_unsupported_on_target IO.FS.createTempDir "*" "uses host filesystem"
register_unsupported_on_target IO.FS.lines         "*" "uses host filesystem"
register_unsupported_on_target IO.FS.Handle.mk       "*" "uses host file handles"
register_unsupported_on_target IO.FS.Handle.lock     "*" "uses host file handles"
register_unsupported_on_target IO.FS.Handle.tryLock  "*" "uses host file handles"
register_unsupported_on_target IO.FS.Handle.unlock   "*" "uses host file handles"
register_unsupported_on_target IO.FS.Handle.isTty    "*" "uses host file handles"
register_unsupported_on_target IO.FS.Handle.flush    "*" "uses host file handles"
register_unsupported_on_target IO.FS.Handle.rewind   "*" "uses host file handles"
register_unsupported_on_target IO.FS.Handle.truncate "*" "uses host file handles"
register_unsupported_on_target IO.FS.Handle.read     "*" "uses host file handles"
register_unsupported_on_target IO.FS.Handle.write    "*" "uses host file handles"
register_unsupported_on_target IO.FS.Handle.getLine  "*" "uses host file handles"
register_unsupported_on_target IO.FS.Handle.putStr   "*" "uses host file handles"
register_unsupported_on_target IO.FS.Handle.lines    "*" "uses host file handles"
register_unsupported_on_target IO.currentDir            "*" "uses host filesystem"
register_unsupported_on_target System.FilePath.readDir  "*" "uses host filesystem"
register_unsupported_on_target System.FilePath.metadata "*" "uses host filesystem"
register_unsupported_on_target System.FilePath.symlinkMetadata "*" "uses host filesystem"
register_unsupported_on_target IO.Prim.setAccessRights  "*" "uses host filesystem"
register_unsupported_on_target IO.setAccessRights "*" "uses host filesystem"

register_unsupported_on_target IO.Process.getCurrentDir "*" "uses host process state"
register_unsupported_on_target IO.Process.setCurrentDir "*" "mutates host process state"
register_unsupported_on_target IO.Process.getPID    "*" "reads host process state"
register_unsupported_on_target IO.Process.spawn    "*" "spawns a host process"
register_unsupported_on_target IO.Process.run      "*" "spawns a host process"
register_unsupported_on_target IO.Process.exit     "*" "exits the host process"
register_unsupported_on_target IO.Process.forceExit "*" "exits the host process"
register_unsupported_on_target IO.Process.output   "*" "spawns a host process"
register_unsupported_on_target IO.Process.Child.wait      "*" "waits on a host process"
register_unsupported_on_target IO.Process.Child.tryWait   "*" "waits on a host process"
register_unsupported_on_target IO.Process.Child.kill      "*" "signals a host process"
register_unsupported_on_target IO.Process.Child.takeStdin "*" "uses host process pipes"
register_unsupported_on_target IO.Process.Child.pid       "*" "reads host process state"

register_unsupported_on_target IO.sleep            "*" "blocks on real time"
register_unsupported_on_target IO.monoMsNow        "*" "reads host real time"
register_unsupported_on_target IO.monoNanosNow     "*" "reads host real time"
register_unsupported_on_target IO.getRandomBytes   "*" "uses host randomness"
register_unsupported_on_target timeit              "*" "uses host runtime instrumentation"
register_unsupported_on_target allocprof           "*" "uses host runtime instrumentation"
register_unsupported_on_target IO.initializing     "*" "uses host initialization state"
register_unsupported_on_target IO.getTID           "*" "reads host thread state"
register_unsupported_on_target IO.getNumHeartbeats "*" "uses host heartbeat state"
register_unsupported_on_target IO.setNumHeartbeats "*" "mutates host heartbeat state"

register_unsupported_on_target IO.getEnv           "*" "reads host environment"
register_unsupported_on_target IO.appPath          "*" "reads host filesystem"
register_unsupported_on_target IO.appDir           "*" "reads host filesystem"

register_unsupported_on_target Thunk.mk            "*" "requires thunk runtime"
register_unsupported_on_target Thunk.pure          "*" "requires thunk runtime"
register_unsupported_on_target Thunk.get           "*" "requires thunk runtime"
register_unsupported_on_target Task.pure           "*" "requires host task runtime"
register_unsupported_on_target Task.spawn          "*" "requires host threads"
register_unsupported_on_target Task.map            "*" "requires host threads"
register_unsupported_on_target Task.bind           "*" "requires host threads"
register_unsupported_on_target Task.get            "*" "requires host task runtime"
register_unsupported_on_target BaseIO.asTask       "*" "requires host task runtime"
register_unsupported_on_target BaseIO.mapTask      "*" "requires host task runtime"
register_unsupported_on_target BaseIO.bindTask     "*" "requires host task runtime"
register_unsupported_on_target IO.checkCanceled    "*" "requires host task runtime"
register_unsupported_on_target IO.cancel           "*" "requires host task runtime"
register_unsupported_on_target IO.getTaskState     "*" "requires host task runtime"
register_unsupported_on_target IO.wait             "*" "requires host task runtime"
register_unsupported_on_target IO.waitAny          "*" "requires host task runtime"
register_unsupported_on_target IO.Promise.new      "*" "requires host promise runtime"
register_unsupported_on_target IO.Promise.resolve  "*" "requires host promise runtime"
register_unsupported_on_target IO.Promise.result?  "*" "requires host promise runtime"
register_unsupported_on_target IO.CancelToken.new  "*" "requires host promise/task runtime"
register_unsupported_on_target IO.CancelToken.set  "*" "requires host promise/task runtime"
register_unsupported_on_target IO.CancelToken.isSet "*" "requires host promise/task runtime"
register_unsupported_on_target IO.CancelToken.onSet "*" "requires host promise/task runtime"

register_unsupported_on_target Std.BaseMutex.new      "*" "requires host mutex runtime"
register_unsupported_on_target Std.BaseMutex.lock     "*" "requires host mutex runtime"
register_unsupported_on_target Std.BaseMutex.tryLock  "*" "requires host mutex runtime"
register_unsupported_on_target Std.BaseMutex.unlock   "*" "requires host mutex runtime"
register_unsupported_on_target Std.Condvar.new        "*" "requires host condition-variable runtime"
register_unsupported_on_target Std.Condvar.wait       "*" "requires host condition-variable runtime"
register_unsupported_on_target Std.Condvar.notifyOne  "*" "requires host condition-variable runtime"
register_unsupported_on_target Std.Condvar.notifyAll  "*" "requires host condition-variable runtime"
register_unsupported_on_target Std.BaseRecursiveMutex.new     "*" "requires host mutex runtime"
register_unsupported_on_target Std.BaseRecursiveMutex.lock    "*" "requires host mutex runtime"
register_unsupported_on_target Std.BaseRecursiveMutex.tryLock "*" "requires host mutex runtime"
register_unsupported_on_target Std.BaseRecursiveMutex.unlock  "*" "requires host mutex runtime"
register_unsupported_on_target Std.BaseSharedMutex.new        "*" "requires host mutex runtime"
register_unsupported_on_target Std.BaseSharedMutex.write      "*" "requires host mutex runtime"
register_unsupported_on_target Std.BaseSharedMutex.tryWrite   "*" "requires host mutex runtime"
register_unsupported_on_target Std.BaseSharedMutex.unlockWrite "*" "requires host mutex runtime"
register_unsupported_on_target Std.BaseSharedMutex.read       "*" "requires host mutex runtime"
register_unsupported_on_target Std.BaseSharedMutex.tryRead    "*" "requires host mutex runtime"
register_unsupported_on_target Std.BaseSharedMutex.unlockRead "*" "requires host mutex runtime"

register_unsupported_on_target IO.getStdin         "*" "reads host stdin"
register_unsupported_on_target IO.getStdout        "*" "uses host stdout"
register_unsupported_on_target IO.getStderr        "*" "uses host stderr"
register_unsupported_on_target IO.setStdin         "*" "mutates host stdio"
register_unsupported_on_target IO.setStdout        "*" "mutates host stdio"
register_unsupported_on_target IO.setStderr        "*" "mutates host stdio"

register_unsupported_on_target Std.Net.IPv4Addr.ofString "*" "uses host networking"
register_unsupported_on_target Std.Net.IPv4Addr.toString "*" "uses host networking"
register_unsupported_on_target Std.Net.IPv6Addr.ofString "*" "uses host networking"
register_unsupported_on_target Std.Net.IPv6Addr.toString "*" "uses host networking"
register_unsupported_on_target Std.Net.interfaceAddresses "*" "uses host networking"
register_unsupported_on_target Std.Internal.UV.Loop.configure "*" "uses host event loop"
register_unsupported_on_target Std.Internal.UV.Loop.alive "*" "uses host event loop"
register_unsupported_on_target Std.Internal.UV.Timer.mk "*" "uses host timer/event loop"
register_unsupported_on_target Std.Internal.UV.Timer.next "*" "uses host timer/event loop"
register_unsupported_on_target Std.Internal.UV.Timer.reset "*" "uses host timer/event loop"
register_unsupported_on_target Std.Internal.UV.Timer.stop "*" "uses host timer/event loop"
register_unsupported_on_target Std.Internal.UV.Timer.cancel "*" "uses host timer/event loop"
register_unsupported_on_target Std.Internal.UV.Signal.mk "*" "uses host signal/event loop"
register_unsupported_on_target Std.Internal.UV.Signal.next "*" "uses host signal/event loop"
register_unsupported_on_target Std.Internal.UV.Signal.stop "*" "uses host signal/event loop"
register_unsupported_on_target Std.Internal.UV.Signal.cancel "*" "uses host signal/event loop"
register_unsupported_on_target Std.Internal.UV.DNS.getAddrInfo "*" "uses host DNS"
register_unsupported_on_target Std.Internal.UV.DNS.getNameInfo "*" "uses host DNS"
register_unsupported_on_target Std.Internal.UV.TCP.Socket.new "*" "uses host networking"
register_unsupported_on_target Std.Internal.UV.TCP.Socket.connect "*" "uses host networking"
register_unsupported_on_target Std.Internal.UV.TCP.Socket.send "*" "uses host networking"
register_unsupported_on_target Std.Internal.UV.TCP.Socket.recv? "*" "uses host networking"
register_unsupported_on_target Std.Internal.UV.TCP.Socket.waitReadable "*" "uses host networking"
register_unsupported_on_target Std.Internal.UV.TCP.Socket.cancelRecv "*" "uses host networking"
register_unsupported_on_target Std.Internal.UV.TCP.Socket.bind "*" "uses host networking"
register_unsupported_on_target Std.Internal.UV.TCP.Socket.listen "*" "uses host networking"
register_unsupported_on_target Std.Internal.UV.TCP.Socket.accept "*" "uses host networking"
register_unsupported_on_target Std.Internal.UV.TCP.Socket.tryAccept "*" "uses host networking"
register_unsupported_on_target Std.Internal.UV.TCP.Socket.cancelAccept "*" "uses host networking"
register_unsupported_on_target Std.Internal.UV.TCP.Socket.shutdown "*" "uses host networking"
register_unsupported_on_target Std.Internal.UV.TCP.Socket.getPeerName "*" "uses host networking"
register_unsupported_on_target Std.Internal.UV.TCP.Socket.getSockName "*" "uses host networking"
register_unsupported_on_target Std.Internal.UV.TCP.Socket.noDelay "*" "uses host networking"
register_unsupported_on_target Std.Internal.UV.TCP.Socket.keepAlive "*" "uses host networking"
register_unsupported_on_target Std.Internal.UV.UDP.Socket.new "*" "uses host networking"
register_unsupported_on_target Std.Internal.UV.UDP.Socket.bind "*" "uses host networking"
register_unsupported_on_target Std.Internal.UV.UDP.Socket.connect "*" "uses host networking"
register_unsupported_on_target Std.Internal.UV.UDP.Socket.send "*" "uses host networking"
register_unsupported_on_target Std.Internal.UV.UDP.Socket.recv "*" "uses host networking"
register_unsupported_on_target Std.Internal.UV.UDP.Socket.waitReadable "*" "uses host networking"
register_unsupported_on_target Std.Internal.UV.UDP.Socket.cancelRecv "*" "uses host networking"
register_unsupported_on_target Std.Internal.UV.UDP.Socket.getPeerName "*" "uses host networking"
register_unsupported_on_target Std.Internal.UV.UDP.Socket.getSockName "*" "uses host networking"
register_unsupported_on_target Std.Internal.UV.UDP.Socket.setBroadcast "*" "uses host networking"
register_unsupported_on_target Std.Internal.UV.UDP.Socket.setMulticastLoop "*" "uses host networking"
register_unsupported_on_target Std.Internal.UV.UDP.Socket.setMulticastTTL "*" "uses host networking"
register_unsupported_on_target Std.Internal.UV.UDP.Socket.setMembership "*" "uses host networking"
register_unsupported_on_target Std.Internal.UV.UDP.Socket.setMulticastInterface "*" "uses host networking"
register_unsupported_on_target Std.Internal.UV.UDP.Socket.setTTL "*" "uses host networking"
register_unsupported_on_target Std.Internal.UV.System.getProcessTitle "*" "uses host process state"
register_unsupported_on_target Std.Internal.UV.System.setProcessTitle "*" "mutates host process state"
register_unsupported_on_target Std.Internal.UV.System.uptime "*" "reads host real time"
register_unsupported_on_target Std.Internal.UV.System.osGetPid "*" "reads host process state"
register_unsupported_on_target Std.Internal.UV.System.osGetPpid "*" "reads host process state"
register_unsupported_on_target Std.Internal.UV.System.cpuInfo "*" "reads host system state"
register_unsupported_on_target Std.Internal.UV.System.cwd "*" "uses host filesystem"
register_unsupported_on_target Std.Internal.UV.System.chdir "*" "mutates host process state"
register_unsupported_on_target Std.Internal.UV.System.osHomedir "*" "uses host filesystem"
register_unsupported_on_target Std.Internal.UV.System.osTmpdir "*" "uses host filesystem"
register_unsupported_on_target Std.Internal.UV.System.osGetPasswd "*" "reads host user database"
register_unsupported_on_target Std.Internal.UV.System.osGetGroup "*" "reads host group database"
register_unsupported_on_target Std.Internal.UV.System.osEnviron "*" "reads host environment"
register_unsupported_on_target Std.Internal.UV.System.osGetenv "*" "reads host environment"
register_unsupported_on_target Std.Internal.UV.System.osSetenv "*" "writes host environment"
register_unsupported_on_target Std.Internal.UV.System.osUnsetenv "*" "writes host environment"
register_unsupported_on_target Std.Internal.UV.System.osGetHostname "*" "reads host network identity"
register_unsupported_on_target Std.Internal.UV.System.osGetPriority "*" "reads host scheduler state"
register_unsupported_on_target Std.Internal.UV.System.osSetPriority "*" "mutates host scheduler state"
register_unsupported_on_target Std.Internal.UV.System.osUname "*" "reads host system state"
register_unsupported_on_target Std.Internal.UV.System.hrtime "*" "reads host real time"
register_unsupported_on_target Std.Internal.UV.System.random "*" "uses host randomness"
register_unsupported_on_target Std.Internal.UV.System.getrusage "*" "reads host process state"
register_unsupported_on_target Std.Internal.UV.System.exePath "*" "uses host filesystem"
register_unsupported_on_target Std.Internal.UV.System.freeMemory "*" "reads host system state"
register_unsupported_on_target Std.Internal.UV.System.totalMemory "*" "reads host system state"
register_unsupported_on_target Std.Internal.UV.System.constrainedMemory "*" "reads host system state"
register_unsupported_on_target Std.Internal.UV.System.availableMemory "*" "reads host system state"

register_unsupported_on_target Std.Time.Timestamp.now "*" "reads host wall clock"
register_unsupported_on_target Std.Time.Database.Windows.getNextTransition "*" "uses host timezone database"
register_unsupported_on_target Std.Time.Database.Windows.getLocalTimeZoneIdentifierAt "*" "uses host timezone database"

register_unsupported_on_target sorryAx           "*" "uses host sorry runtime"
register_unsupported_on_target dbgTrace          "*" "uses host debug output"
register_unsupported_on_target dbgTraceIfShared  "*" "uses host debug output"
register_unsupported_on_target dbgStackTrace     "*" "uses host debug output"
register_unsupported_on_target dbgSleep          "*" "blocks on host real time"
register_unsupported_on_target ShareCommon.Object.eq "*" "uses host share-common runtime"
register_unsupported_on_target ShareCommon.Object.hash "*" "uses host share-common runtime"
register_unsupported_on_target ShareCommon.State.shareCommon "*" "uses host share-common runtime"
register_unsupported_on_target ShareCommon.shareCommon' "*" "uses host share-common runtime"

register_unsupported_on_target System.Platform.getNumBits "*" "uses host platform query"
register_unsupported_on_target System.Platform.getIsWindows "*" "uses host platform query"
register_unsupported_on_target System.Platform.getIsOSX "*" "uses host platform query"
register_unsupported_on_target System.Platform.getIsEmscripten "*" "uses host platform query"
register_unsupported_on_target System.Platform.getTarget "*" "uses host platform query"

register_unsupported_on_target Int8.add          "*" "requires signed fixed-width Int runtime"
register_unsupported_on_target Int8.sub          "*" "requires signed fixed-width Int runtime"
register_unsupported_on_target Int8.mul          "*" "requires signed fixed-width Int runtime"
register_unsupported_on_target Int8.div          "*" "requires signed fixed-width Int runtime"
register_unsupported_on_target Int8.mod          "*" "requires signed fixed-width Int runtime"
register_unsupported_on_target Int8.decLt        "*" "requires signed fixed-width Int runtime"
register_unsupported_on_target Int8.decLe        "*" "requires signed fixed-width Int runtime"
register_unsupported_on_target Int16.add         "*" "requires signed fixed-width Int runtime"
register_unsupported_on_target Int16.sub         "*" "requires signed fixed-width Int runtime"
register_unsupported_on_target Int16.mul         "*" "requires signed fixed-width Int runtime"
register_unsupported_on_target Int16.div         "*" "requires signed fixed-width Int runtime"
register_unsupported_on_target Int16.mod         "*" "requires signed fixed-width Int runtime"
register_unsupported_on_target Int16.decLt       "*" "requires signed fixed-width Int runtime"
register_unsupported_on_target Int16.decLe       "*" "requires signed fixed-width Int runtime"
register_unsupported_on_target Int32.add         "*" "requires signed fixed-width Int runtime"
register_unsupported_on_target Int32.sub         "*" "requires signed fixed-width Int runtime"
register_unsupported_on_target Int32.mul         "*" "requires signed fixed-width Int runtime"
register_unsupported_on_target Int32.div         "*" "requires signed fixed-width Int runtime"
register_unsupported_on_target Int32.mod         "*" "requires signed fixed-width Int runtime"
register_unsupported_on_target Int32.decLt       "*" "requires signed fixed-width Int runtime"
register_unsupported_on_target Int32.decLe       "*" "requires signed fixed-width Int runtime"
register_unsupported_on_target Int64.add         "*" "requires signed fixed-width Int runtime"
register_unsupported_on_target Int64.sub         "*" "requires signed fixed-width Int runtime"
register_unsupported_on_target Int64.mul         "*" "requires signed fixed-width Int runtime"
register_unsupported_on_target Int64.div         "*" "requires signed fixed-width Int runtime"
register_unsupported_on_target Int64.mod         "*" "requires signed fixed-width Int runtime"
register_unsupported_on_target Int64.decLt       "*" "requires signed fixed-width Int runtime"
register_unsupported_on_target Int64.decLe       "*" "requires signed fixed-width Int runtime"
register_unsupported_on_target ISize.add         "*" "requires signed fixed-width Int runtime"
register_unsupported_on_target ISize.sub         "*" "requires signed fixed-width Int runtime"
register_unsupported_on_target ISize.mul         "*" "requires signed fixed-width Int runtime"
register_unsupported_on_target ISize.div         "*" "requires signed fixed-width Int runtime"
register_unsupported_on_target ISize.mod         "*" "requires signed fixed-width Int runtime"
register_unsupported_on_target ISize.decLt       "*" "requires signed fixed-width Int runtime"
register_unsupported_on_target ISize.decLe       "*" "requires signed fixed-width Int runtime"

register_unsupported_on_target Float.add         "*" "requires full Float runtime"
register_unsupported_on_target Float.sub         "*" "requires full Float runtime"
register_unsupported_on_target Float.mul         "*" "requires full Float runtime"
register_unsupported_on_target Float.div         "*" "requires full Float runtime"
register_unsupported_on_target Float.neg         "*" "requires full Float runtime"
register_unsupported_on_target Float.ofBits      "*" "requires full Float runtime"
register_unsupported_on_target Float.toBits      "*" "requires full Float runtime"
register_unsupported_on_target Float.beq         "*" "requires full Float runtime"
register_unsupported_on_target Float.decLt       "*" "requires full Float runtime"
register_unsupported_on_target Float.decLe       "*" "requires full Float runtime"
register_unsupported_on_target Float.toString    "*" "requires full Float runtime"
register_unsupported_on_target Float.toUInt8     "*" "requires full Float runtime"
register_unsupported_on_target Float.toUInt16    "*" "requires full Float runtime"
register_unsupported_on_target Float.toUInt32    "*" "requires full Float runtime"
register_unsupported_on_target Float.toUInt64    "*" "requires full Float runtime"
register_unsupported_on_target Float.toUSize     "*" "requires full Float runtime"
register_unsupported_on_target Float.isNaN       "*" "requires full Float runtime"
register_unsupported_on_target Float.isFinite    "*" "requires full Float runtime"
register_unsupported_on_target Float.isInf       "*" "requires full Float runtime"
register_unsupported_on_target Float.frExp       "*" "requires full Float runtime"
register_unsupported_on_target Float.scaleB      "*" "requires full Float runtime"
register_unsupported_on_target Float.toFloat32   "*" "requires full Float runtime"
register_unsupported_on_target Float.sin         "*" "requires libm"
register_unsupported_on_target Float.cos         "*" "requires libm"
register_unsupported_on_target Float.tan         "*" "requires libm"
register_unsupported_on_target Float.asin        "*" "requires libm"
register_unsupported_on_target Float.acos        "*" "requires libm"
register_unsupported_on_target Float.atan        "*" "requires libm"
register_unsupported_on_target Float.atan2       "*" "requires libm"
register_unsupported_on_target Float.sinh        "*" "requires libm"
register_unsupported_on_target Float.cosh        "*" "requires libm"
register_unsupported_on_target Float.tanh        "*" "requires libm"
register_unsupported_on_target Float.asinh       "*" "requires libm"
register_unsupported_on_target Float.acosh       "*" "requires libm"
register_unsupported_on_target Float.atanh       "*" "requires libm"
register_unsupported_on_target Float.exp         "*" "requires libm"
register_unsupported_on_target Float.exp2        "*" "requires libm"
register_unsupported_on_target Float.log         "*" "requires libm"
register_unsupported_on_target Float.log2        "*" "requires libm"
register_unsupported_on_target Float.log10       "*" "requires libm"
register_unsupported_on_target Float.pow         "*" "requires libm"
register_unsupported_on_target Float.sqrt        "*" "requires libm"
register_unsupported_on_target Float.cbrt        "*" "requires libm"
register_unsupported_on_target Float.ceil        "*" "requires libm"
register_unsupported_on_target Float.floor       "*" "requires libm"
register_unsupported_on_target Float.round       "*" "requires libm"
register_unsupported_on_target Float.abs         "*" "requires libm"
register_unsupported_on_target UInt8.toFloat     "*" "requires full Float runtime"
register_unsupported_on_target Float.toInt8      "*" "requires full Float runtime"
register_unsupported_on_target Float.toInt16     "*" "requires full Float runtime"
register_unsupported_on_target Float.toInt32     "*" "requires full Float runtime"
register_unsupported_on_target Float.toInt64     "*" "requires full Float runtime"
register_unsupported_on_target Float.toISize     "*" "requires full Float runtime"
register_unsupported_on_target Int8.toFloat      "*" "requires full Float runtime"
register_unsupported_on_target Int16.toFloat     "*" "requires full Float runtime"
register_unsupported_on_target Int32.toFloat     "*" "requires full Float runtime"
register_unsupported_on_target Int64.toFloat     "*" "requires full Float runtime"

register_unsupported_on_target Float32.add       "*" "requires full Float32 runtime"
register_unsupported_on_target Float32.sub       "*" "requires full Float32 runtime"
register_unsupported_on_target Float32.mul       "*" "requires full Float32 runtime"
register_unsupported_on_target Float32.div       "*" "requires full Float32 runtime"
register_unsupported_on_target Float32.neg       "*" "requires full Float32 runtime"
register_unsupported_on_target Float32.ofBits    "*" "requires full Float32 runtime"
register_unsupported_on_target Float32.toBits    "*" "requires full Float32 runtime"
register_unsupported_on_target Float32.beq       "*" "requires full Float32 runtime"
register_unsupported_on_target Float32.decLt     "*" "requires full Float32 runtime"
register_unsupported_on_target Float32.decLe     "*" "requires full Float32 runtime"
register_unsupported_on_target Float32.toString  "*" "requires full Float32 runtime"
register_unsupported_on_target Float32.toUInt8   "*" "requires full Float32 runtime"
register_unsupported_on_target Float32.toUInt16  "*" "requires full Float32 runtime"
register_unsupported_on_target Float32.toUInt32  "*" "requires full Float32 runtime"
register_unsupported_on_target Float32.toUInt64  "*" "requires full Float32 runtime"
register_unsupported_on_target Float32.toUSize   "*" "requires full Float32 runtime"
register_unsupported_on_target Float32.isNaN     "*" "requires full Float32 runtime"
register_unsupported_on_target Float32.isFinite  "*" "requires full Float32 runtime"
register_unsupported_on_target Float32.isInf     "*" "requires full Float32 runtime"
register_unsupported_on_target Float32.frExp     "*" "requires full Float32 runtime"
register_unsupported_on_target Float32.scaleB    "*" "requires full Float32 runtime"
register_unsupported_on_target Float32.toFloat   "*" "requires full Float32 runtime"
register_unsupported_on_target Float32.sin       "*" "requires libm"
register_unsupported_on_target Float32.cos       "*" "requires libm"
register_unsupported_on_target Float32.tan       "*" "requires libm"
register_unsupported_on_target Float32.asin      "*" "requires libm"
register_unsupported_on_target Float32.acos      "*" "requires libm"
register_unsupported_on_target Float32.atan      "*" "requires libm"
register_unsupported_on_target Float32.atan2     "*" "requires libm"
register_unsupported_on_target Float32.sinh      "*" "requires libm"
register_unsupported_on_target Float32.cosh      "*" "requires libm"
register_unsupported_on_target Float32.tanh      "*" "requires libm"
register_unsupported_on_target Float32.asinh     "*" "requires libm"
register_unsupported_on_target Float32.acosh     "*" "requires libm"
register_unsupported_on_target Float32.atanh     "*" "requires libm"
register_unsupported_on_target Float32.exp       "*" "requires libm"
register_unsupported_on_target Float32.exp2      "*" "requires libm"
register_unsupported_on_target Float32.log       "*" "requires libm"
register_unsupported_on_target Float32.log2      "*" "requires libm"
register_unsupported_on_target Float32.log10     "*" "requires libm"
register_unsupported_on_target Float32.pow       "*" "requires libm"
register_unsupported_on_target Float32.sqrt      "*" "requires libm"
register_unsupported_on_target Float32.cbrt      "*" "requires libm"
register_unsupported_on_target Float32.ceil      "*" "requires libm"
register_unsupported_on_target Float32.floor     "*" "requires libm"
register_unsupported_on_target Float32.round     "*" "requires libm"
register_unsupported_on_target Float32.abs       "*" "requires libm"
register_unsupported_on_target UInt8.toFloat32   "*" "requires full Float32 runtime"
register_unsupported_on_target UInt16.toFloat32  "*" "requires full Float32 runtime"
register_unsupported_on_target UInt32.toFloat32  "*" "requires full Float32 runtime"
register_unsupported_on_target UInt64.toFloat32  "*" "requires full Float32 runtime"
register_unsupported_on_target USize.toFloat32   "*" "requires full Float32 runtime"
register_unsupported_on_target Float32.toInt8    "*" "requires full Float32 runtime"
register_unsupported_on_target Float32.toInt16   "*" "requires full Float32 runtime"
register_unsupported_on_target Float32.toInt32   "*" "requires full Float32 runtime"
register_unsupported_on_target Float32.toInt64   "*" "requires full Float32 runtime"
register_unsupported_on_target Float32.toISize   "*" "requires full Float32 runtime"
register_unsupported_on_target Int8.toFloat32    "*" "requires full Float32 runtime"
register_unsupported_on_target Int16.toFloat32   "*" "requires full Float32 runtime"
register_unsupported_on_target Int32.toFloat32   "*" "requires full Float32 runtime"
register_unsupported_on_target Int64.toFloat32   "*" "requires full Float32 runtime"
register_unsupported_on_target ISize.toFloat32   "*" "requires full Float32 runtime"

register_unsupported_on_target String.ofList     "*" "requires full String runtime"
register_unsupported_on_target String.mk         "*" "requires full String runtime"
register_unsupported_on_target String.utf8ByteSize "*" "requires full UTF-8 string runtime"
register_unsupported_on_target String.hash       "*" "requires String hash runtime"
register_unsupported_on_target String.decidableLT "*" "requires String ordering runtime"
register_unsupported_on_target String.extract    "*" "requires full UTF-8 string runtime"
register_unsupported_on_target String.Pos.set    "*" "requires full UTF-8 string runtime"
register_unsupported_on_target String.Pos.Raw.isValid "*" "requires full UTF-8 string runtime"
register_unsupported_on_target String.Pos.Raw.extract "*" "requires full UTF-8 string runtime"
register_unsupported_on_target String.Pos.Raw.get "*" "requires full UTF-8 string runtime"
register_unsupported_on_target String.Pos.Raw.get? "*" "requires full UTF-8 string runtime"
register_unsupported_on_target String.Pos.Raw.get! "*" "requires full UTF-8 string runtime"
register_unsupported_on_target String.Pos.Raw.next "*" "requires full UTF-8 string runtime"
register_unsupported_on_target String.Pos.Raw.prev "*" "requires full UTF-8 string runtime"
register_unsupported_on_target String.Pos.Raw.atEnd "*" "requires full UTF-8 string runtime"
register_unsupported_on_target String.Pos.Raw.get' "*" "requires full UTF-8 string runtime"
register_unsupported_on_target String.Pos.Raw.next' "*" "requires full UTF-8 string runtime"
register_unsupported_on_target String.get        "*" "requires full UTF-8 string runtime"
register_unsupported_on_target String.get?       "*" "requires full UTF-8 string runtime"
register_unsupported_on_target String.get!       "*" "requires full UTF-8 string runtime"
register_unsupported_on_target String.next       "*" "requires full UTF-8 string runtime"
register_unsupported_on_target String.prev       "*" "requires full UTF-8 string runtime"
register_unsupported_on_target String.atEnd      "*" "requires full UTF-8 string runtime"
register_unsupported_on_target String.get'       "*" "requires full UTF-8 string runtime"
register_unsupported_on_target String.next'      "*" "requires full UTF-8 string runtime"
register_unsupported_on_target String.Internal.posOf "*" "requires full UTF-8 string runtime"
register_unsupported_on_target String.Internal.offsetOfPos "*" "requires full UTF-8 string runtime"
register_unsupported_on_target String.Internal.extract "*" "requires full UTF-8 string runtime"
register_unsupported_on_target String.Internal.pushn "*" "requires full UTF-8 string runtime"
register_unsupported_on_target String.Internal.next "*" "requires full UTF-8 string runtime"
register_unsupported_on_target String.Internal.foldl "*" "requires full UTF-8 string runtime"
register_unsupported_on_target String.Internal.isPrefixOf "*" "requires full UTF-8 string runtime"
register_unsupported_on_target String.Internal.any "*" "requires full UTF-8 string runtime"
register_unsupported_on_target String.Internal.contains "*" "requires full UTF-8 string runtime"
register_unsupported_on_target String.Internal.get "*" "requires full UTF-8 string runtime"
register_unsupported_on_target String.Internal.capitalize "*" "requires full UTF-8 string runtime"
register_unsupported_on_target String.Internal.atEnd "*" "requires full UTF-8 string runtime"
register_unsupported_on_target String.Internal.nextWhile "*" "requires full UTF-8 string runtime"
register_unsupported_on_target String.Internal.trim "*" "requires full UTF-8 string runtime"
register_unsupported_on_target String.Internal.intercalate "*" "requires full UTF-8 string runtime"
register_unsupported_on_target String.Internal.front "*" "requires full UTF-8 string runtime"
register_unsupported_on_target String.Internal.drop "*" "requires full UTF-8 string runtime"
register_unsupported_on_target String.Internal.dropRight "*" "requires full UTF-8 string runtime"
register_unsupported_on_target String.Internal.getUTF8Byte "*" "requires full UTF-8 string runtime"
register_unsupported_on_target String.Slice.Pattern.Internal.memcmpStr "*" "requires full UTF-8 string runtime"
register_unsupported_on_target String.Pos.Raw.Internal.sub "*" "requires full UTF-8 string runtime"
register_unsupported_on_target String.Pos.Raw.Internal.min "*" "requires full UTF-8 string runtime"
register_unsupported_on_target Substring.Raw.Internal.toString "*" "requires substring runtime"
register_unsupported_on_target Substring.Raw.Internal.drop "*" "requires substring runtime"
register_unsupported_on_target Substring.Raw.Internal.front "*" "requires substring runtime"
register_unsupported_on_target Substring.Raw.Internal.takeWhile "*" "requires substring runtime"
register_unsupported_on_target Substring.Raw.Internal.extract "*" "requires substring runtime"
register_unsupported_on_target Substring.Raw.Internal.all "*" "requires substring runtime"
register_unsupported_on_target Substring.Raw.Internal.beq "*" "requires substring runtime"
register_unsupported_on_target Substring.Raw.Internal.isEmpty "*" "requires substring runtime"
register_unsupported_on_target Substring.Raw.Internal.get "*" "requires substring runtime"
register_unsupported_on_target Substring.Raw.Internal.prev "*" "requires substring runtime"
register_unsupported_on_target String.Slice.hash "*" "requires String.Slice hash runtime"
register_unsupported_on_target USize.repr        "*" "requires string-of-usize runtime"
register_unsupported_on_target ByteSlice.beq     "*" "requires ByteSlice runtime"
