/*
Copyright (c) 2026 Lean FRO, LLC. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.

WASI entrypoint adapter for the wasm32-wasip1 target. Plays the same
role as `src/runtime/sbf/entrypoint.c`: defines the platform-required
entry symbol and forwards to a per-build glue function generated by
`leanc --target=wasm32-wasip1` (which knows the user's exported
init / entry symbols by reading the `.bc`'s symbol table).

WASI command modules are expected to export `_start` taking no args
and returning no value; the runtime calls it once and reads the exit
code from `proc_exit`. We:
  1. Run the Lean module initialiser chain (`lean_wasm_module_init`,
     wired by leanc to point at `initialize_<UserMod>`).
  2. Call the user's entry (`lean_wasm_invoke_entry`, also wired by
     leanc to dispatch to `lean_wasm_main` / `lean_wasm_main_string` /
     etc. depending on which entry the user exported).
  3. Forward the entry's return value as the process exit code via
     `wasi_proc_exit`, so the test harness can observe it.
*/

#include <stdint.h>

/* Per-build glue, written by leanc. */
extern void *lean_wasm_module_init(uint8_t builtin, void *world);
extern uint64_t lean_wasm_invoke_entry(void);

/* WASI proc_exit (raw import; no libc). */
__attribute__((import_module("wasi_snapshot_preview1"),
               import_name("proc_exit"),
               noreturn))
extern void wasi_proc_exit(uint32_t code);

__attribute__((export_name("_start")))
void _start(void) {
    /* Run the user-module initialiser. The `1` argument is `builtin =
       true`, matching the convention used by Lean's host runtime. We
       don't introspect the result on the WASM target — modules that
       return `error` from init are expected to panic at the trap site
       inside the runtime, not silently return a non-zero IO result. */
    /* World token is opaque on freestanding wasm; pass NULL. */
    (void)lean_wasm_module_init(1, (void *)0);

    /* Call the user's entry. By convention, the entry returns a
       UInt64 we forward as the exit code; programs that want to
       signal "ok" simply return 0. */
    uint64_t rc = lean_wasm_invoke_entry();

    /* `proc_exit` doesn't return; this satisfies wasm-ld and lets the
       host observe the exit code. */
    wasi_proc_exit((uint32_t)(rc & 0xFFFFFFFFu));
    __builtin_unreachable();
}
